services:
  - type: web
    name: leetcode-tracker
    runtime: node
    plan: free
    env: node
    region: oregon
    buildCommand: npm install && npm run build && node deploy-simple.cjs
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false